apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    namespace 'com.tapmame.pad'
    compileSdk 34
    defaultConfig {
        applicationId "com.tapmame.pad"
        minSdkVersion 29
        targetSdkVersion 34
        versionCode 1
        versionName "0.1"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = '17' }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:1.9.24"
    // SMB/CIFS client for the LAN NAS ROM browser
    implementation "eu.agno3.jcifs:jcifs-ng:2.1.10"
}
